name = "moon"
description = ""
homepage = ""
tags = []
min_version = 0.1

SectionPagesMenu = "main"

[author]
  name = "Sohan Subhash"
  homepage = "https://inclusive-components.design"

[taxonomies]
  tag = "tags"
  wcag = "wcag"
  principle = "principles"
